export const data = [
  {
    title:
      'Purina Pro Plan Sensitive Skin & Stomach Adult Dry Dog Food - Salmon & Rice',
    content:
      "Nurture your dog's sensitive skin and stomach with Purina Pro Plan Sensitive Skin and Stomach Salmon and Rice Formula adult dry dog food. Nutrient-rich salmon is the first ingredient in this high protein dog food. Plus, the prebiotic fiber in this dog food for sensitive stomachs nourishes the beneficial bacteria found in your dog's intestine for his digestive health. Antioxidants deliver immune support for your dog, while rice and oat meal provide easily digestible sources of carbohydrates. Meanwhile, fish oil for dogs - rich in omega-3 fatty acids EPA and DHA - helps support healthy joints, while omega-6 fatty acids and vitamin A nourish your dog's skin and keep his coat looking healthy. This dog kibble is formulated without corn, wheat, soy or artificial colors or flavors. Help keep him healthy, happy and feeling extraordinary with Purina Pro Plan Sensitive Skin and Stomach Salmon and Rice Formula adult dry dog food",
    category: 'Chien',
    typefood: 'Dry Dog Food',
    market: ' Purina Pro Plan',
    quantity: '40Lb',
    images: [
      'https://s7d2.scene7.com/is/image/PetSmart/5339575?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5339575?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5339575_alt1?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5339575_alt2?$CLEARjpg$',
    ],
    priceForPersonal: '89.98',
    priceForCompany: '92.99',
    // "published": 'private',
    stock: 38,
  },
  {
    title:
      'Purina Pro Plan Complete Essentials Adult Dry Dog Food - High Protein, Probiotics, Chicken & Rice',
    content:
      "Get your dog excited about mealtime when you serve him Purina Pro Plan Brand Dog Food Shredded Blend Chicken and Rice Formula adult dry dog food. Real chicken as the first ingredient and rice, which is an excellent source of carbohydrates for energy, along with other high-quality ingredients create a wholesome meal with great flavor. The hard kibble and tender shredded pieces provide a texture sure to keep him engaged with every bite. Feel good about serving your dog 100 percent complete and balanced nutrition, and take comfort knowing that each serving contains a high level of protein to help dogs maintain an ideal body condition. Vitamin A and linoleic acid, an omega-6 fatty acid, promote healthy skin and coat to keep him looking great, and guaranteed live probiotics help to support his digestive health. Formulated with high-quality protein and other essential nutrients, this Purina Pro Plan COMPLETE ESSENTIALS recipe helps support your beloved pet's overall health and wellness.",
    category: 'Chien',
    typefood: 'Adult dry dog',
    market: 'Purina Pro Plan',
    quantity: '35Lb',
    images: [
      'https://s7d2.scene7.com/is/image/PetSmart/5135727?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5135727?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5135727_alt1?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5135727_alt2?$CLEARjpg$',
    ],
    priceForPersonal: '69.98',
    priceForCompany: '70.99',
    // "published": 'private',
    stock: 68,
  },
  {
    title:
      'Authority® Everyday Health Large Breed Adult Dry Dog Food - Chickene',
    content:
      "Get your dog excited about mealtime when you serve him Purina Pro Plan Brand Dog Food Shredded Blend Chicken and Rice Formula adult dry dog food. Real chicken as the first ingredient and rice, which is an excellent source of carbohydrates for energy, along with other high-quality ingredients create a wholesome meal with great flavor. The hard kibble and tender shredded pieces provide a texture sure to keep him engaged with every bite. Feel good about serving your dog 100 percent complete and balanced nutrition, and take comfort knowing that each serving contains a high level of protein to help dogs maintain an ideal body condition. Vitamin A and linoleic acid, an omega-6 fatty acid, promote healthy skin and coat to keep him looking great, and guaranteed live probiotics help to support his digestive health. Formulated with high-quality protein and other essential nutrients, this Purina Pro Plan COMPLETE ESSENTIALS recipe helps support your beloved pet's overall health and wellness.",
    category: 'Chien',
    typefood: 'Adult dry dog',
    market: 'Purina Pro Plan',
    quantity: '35Lb',
    images: [
      'https://s7d2.scene7.com/is/image/PetSmart/5279157?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5279157?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5279157_alt1?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5279157_alt1?$CLEARjpg$',
    ],
    priceForPersonal: '56.98',
    priceForCompany: '60.99',
    // "published": 'private',
    stock: 68,
  },
  {
    title:
      'Authority® Sensitive Stomach & Skin All Life Stage Dry Dog Food - Salmon',
    content:
      'Help your dog to enjoy proper digestion along with healthy skin and a shiny coat by serving Authority Salmon & Rice Formula Sensitive Stomach & Skin Dry Dog Food. This delicious dry blend features the great taste of salmon in each and every bite, and is formulated to support digestion and nourish the skin and coat. Only at PetSmart.',
    category: 'Chien',
    typefood: 'Dry Dog Food',
    market: 'Authority',
    quantity: '34Lb',

    images: [
      'https://s7d2.scene7.com/is/image/PetSmart/5309276?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5309276?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5309276_alt1?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5309276_alt1?$CLEARjpg$',
    ],
    priceForPersonal: '59.98',
    priceForCompany: '42.99',
    // "published": 'private',
    stock: 38,
  },
  {
    title:
      "Hill's® Science Diet® Sensitive Stomach & Skin Adult Dry Dog Food - Chicken & Barley",
    content:
      "Hill's Science Diet Sensitive Stomach & Skin dry dog food is gentle on stomachs while nourishing skin and promoting a lustrous coat. This food features beet pulp, a nourishing prebiotic fiber, and is highly digestible and gentle on the stomach. It also includes Vitamin E and Omega-6 fatty acids for skin and coat nourishment.",
    category: 'Chien',
    typefood: 'Adult dry dog',
    market: "Hill's Science Diet",
    quantity: '30Lb',
    images: [
      'https://s7d2.scene7.com/is/image/PetSmart/5154856?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5154856?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5154856_alt1?$CLEARjpg$',
      'https://s7d2.scene7.com/is/image/PetSmart/5154856_alt4?$CLEARjpg$',
    ],
    priceForPersonal: '79.99',
    priceForCompany: '69.99',
    // "published": 'private',
    stock: 38,
  },
  {
    title: 'VFS® POWERCAT™ Herring & Salmon for Cats',
    content:
      'VFS POWERCAT is obligate carnivore nutrition specifically formulated to match the needs of the unique feline metabolism.  VFS POWERCAT is a high meat-based protein diet paired with ultra-low carbohydrates which provides the carnivorous amino acids required by hypercarnivores to help promote strong muscles and a lean and fit body condition.  VFS POWERCAT is the perfect diet for your hypercarnivorous feline! ',
    category: 'Chien',
    typefood: 'Salmon for Cats',
    market: 'VFS POWERCAT',
    quantity: '11Lb',
    images: [
      'https://shop.mysquarepet.com/cdn/shop/products/SquarePet_VFS_Powercat_Herring_11lb_1024x1024@2x.png?v=1658867289',
      'https://shop.mysquarepet.com/cdn/shop/products/SquarePet_VFS_Powercat_Herring_11lb_1024x1024@2x.png?v=1658867289',
      'https://shop.mysquarepet.com/cdn/shop/files/PCHSInfo_1024x1024@2x.png?v=1694709262',
      'https://shop.mysquarepet.com/cdn/shop/files/111014_PT1_1024x1024@2x.png?v=1694709262',
    ],
    priceForPersonal: '67.99',
    priceForCompany: '60.99',
    // "published": 'private',
    stock: 38,
  },
  {
    title: 'NATURAL BIRD FOOD WITH ADDED VITAMINS AND MINERALS',
    content:
      'Fresh, wholesome natural bird food made with vegetables & formulated with vitamins & minerals',
    category: 'Oiseaux',
    typefood: 'Natural bird Food',
    market: 'VFS POWERCAT',
    quantity: '3Lb',
    images: [
      'https://woofmeownh.com/cdn/shop/products/unnamed_95481dee-7d7c-451d-8510-f1a8fc7aabeb_1024x1024@2x.jpg?v=1661882314',
      'https://shop.mysquarepet.com/cdn/shop/products/SquarePet_VFS_Powercat_Herring_11lb_1024x1024@2x.png?v=1658867289',
      'https://shop.mysquarepet.com/cdn/shop/files/PCHSInfo_1024x1024@2x.png?v=1694709262',
      'https://shop.mysquarepet.com/cdn/shop/files/111014_PT1_1024x1024@2x.png?v=1694709262',
    ],
    priceForPersonal: '23.99',
    priceForCompany: '20.99',
    // "published": 'private',
    stock: 38,
  },
  {
    title: 'Higgins Vita Seed Natural Blend Parakeet',
    content:
      'Fresh, wholesome natural bird food made with vegetables & formulated with vitamins & minerals',
    category: 'Oiseaux',
    typefood: 'Natural bird Food',
    market: 'VFS POWERCAT',
    quantity: '3Lb',
    images: [
      'https://woofmeownh.com/cdn/shop/products/unnamed_6aa140f3-3d98-43c5-90cb-b94168420d16_1024x1024@2x.jpg?v=1661881773',
      'https://shop.mysquarepet.com/cdn/shop/products/SquarePet_VFS_Powercat_Herring_11lb_1024x1024@2x.png?v=1658867289',
      'https://woofmeownh.com/cdn/shop/products/unnamed_1b70ab4e-43ba-4f73-b0e4-7ee8b5729586_1024x1024@2x.jpg?v=1661881773',
      'https://woofmeownh.com/cdn/shop/products/unnamed_20b16ca6-308f-4fec-b697-7d879626f22f_1024x1024@2x.jpg?v=1661881773',
    ],
    priceForPersonal: '8.99',
    priceForCompany: '6.99',
    // "published": 'private',
    stock: 38,
  },
  {
    title: 'Cat Meal Variety Pack (12 Pouches)',
    content:
      "Luke's Chicken N' Pumpkin' is a simple wholesome meal made with boneless white and dark chicken meat and slowly cooked in small batches with only 8 natural ingredients.adventure!",
    category: 'Chats',
    typefood: "Luke's Chicken",
    market: 'VFS POWERCAT',
    quantity: '3Lb',
    images: [
      'https://portlandpetfoodcompany.com/cdn/shop/products/12pack-CatMeals_2048x2048.png?v=1668120651',
      'https://portlandpetfoodcompany.com/cdn/shop/products/12pack-CatMeals_2048x2048.png?v=1668120651',
      'https://portlandpetfoodcompany.com/cdn/shop/products/220622_PPF_Cats_64521_ca50795d-2b78-45ba-a99c-71c5f19b01a6_2048x2048.jpg?v=1668120651',
      'https://portlandpetfoodcompany.com/cdn/shop/products/PPFC-Cat-Food-Main-images-Image-6c_1_2048x2048.jpg?v=1668122065',
    ],
    priceForPersonal: '40.99',
    priceForCompany: '38.99',
    // "published": 'private',
    stock: 38,
  },
  {
    title: 'Energy Pet – Adult Cat',
    content:
      'Happy Cat Minkas Hairball Control contains special types of raw fibre. These help to minimize cat hairballs and assist in gentle elimination via the gastro-intestinal tract. This balanced complete diet is perfect for adult cats and provides your kitty with everything they need. For a long and healthy life. Our recipe, with its high proportion of high-value animal protein, is 100% natural and balanced. The delicious dry food contains many vitamins and minerals, and supports the immune system. Our recipes are naturally free from artificial flavourings and preservatives.',
    category: 'Chats',
    typefood: 'Energy Adult Cat',
    market: 'VFS POWERCAT',
    quantity: '4kg',
    images: [
      'https://petshoplebanon.com/wp-content/uploads/2022/05/best_Cat_food_in_Lebanon_Happy-Cat-%E2%80%93-Hairball-Control-Poultry-1.5kg_2-3_From_Pet_Shop_Lebanon-700x1050.png.webp',
      'https://petshoplebanon.com/wp-content/uploads/2022/05/best_Cat_food_in_Lebanon_Happy-Cat-%E2%80%93-Hairball-Control-Poultry-1.5kg_2-3_From_Pet_Shop_Lebanon-700x1050.png.webp',
      'https://petshoplebanon.com/wp-content/uploads/2022/05/02_Minkas-HairballControl-Kroket.jpg.webp',
      'https://petshoplebanon.com/wp-content/uploads/2022/05/08_Minkas-BestRatedBrand_600x600.jpg.webp',
    ],
    priceForPersonal: '20.99',
    priceForCompany: '11.99',
    // "published": 'private',
    stock: 38,
  },
  {
    title: 'Kit Cat Classic 32 Dry Cat Food 1.2kg',
    content:
      'Happy Cat Minkas Hairball Control contains special types of raw fibre. These help to minimize cat hairballs and assist in gentle elimination via the gastro-intestinal tract. This balanced complete diet is perfect for adult cats and provides your kitty with everything they need. For a long and healthy life. Our recipe, with its high proportion of high-value animal protein, is 100% natural and balanced. The delicious dry food contains many vitamins and minerals, and supports the immune system. Our recipes are naturally free from artificial flavourings and preservatives.',
    category: 'Chats',
    typefood: 'Dry Cat Food',
    market: 'PET EXPRESS',
    quantity: '4kg',
    images: [
      'https://www.petexpress.com.ph/cdn/shop/files/10243702KitCatClassic32DryCatFoodA_400x.png?v=1693985067',
      'https://www.petexpress.com.ph/cdn/shop/files/10243702KitCatClassic32DryCatFoodA_400x.png?v=1693985067',
      'https://www.petexpress.com.ph/cdn/shop/files/10243702KitCatClassic32DryCatFoodB_400x.png?v=1693985068',
      'https://www.petexpress.com.ph/cdn/shop/files/10243702KitCatClassic32DryCatFoodC_400x.png?v=1693985068',
    ],
    priceForPersonal: '54.99',
    priceForCompany: '49.99',
    // "published": 'private',
    stock: 68,
  },
  {
    title: 'Meow Mix Dry Cat Food',
    content:
      'Specially formulated to help control hairballs before they start, Meow Mix Hairball Control cat food is a tasty mix with chicken, turkey, salmon & ocean fish flavors. This wholesome recipe filled with essential vitamins and minerals along with high-quality protein make mealtimes irresistible!',
    category: 'Chats',
    typefood: 'Dry Cat Food',
    market: 'PET EXPRESS',
    quantity: '3.15lb',
    images: [
      'https://shop.qa.foodlion.com/cdn-cgi/image/f=auto,q=80,dpr=1,h=324,w=324/https://d2d8wwwkmhfcva.cloudfront.net/800x/filters:fill(FFF,true):format(jpg)/d2lnr5mha7bycj.cloudfront.net/product-image/file/large_30ec0c81-344f-4012-befa-0d4f70ee28c2.jpg',
      'https://shop.qa.foodlion.com/cdn-cgi/image/f=auto,q=80,dpr=1,h=324,w=324/https://d2d8wwwkmhfcva.cloudfront.net/800x/filters:fill(FFF,true):format(jpg)/d2lnr5mha7bycj.cloudfront.net/product-image/file/large_30ec0c81-344f-4012-befa-0d4f70ee28c2.jpg',
      'https://shop.qa.foodlion.com/cdn-cgi/image/f=auto,q=80,dpr=1,h=324,w=324/https://d2d8wwwkmhfcva.cloudfront.net/800x/filters:fill(FFF,true):format(jpg)/d2lnr5mha7bycj.cloudfront.net/product-image/file/large_50d4b0f7-3b21-4df1-8735-bfd839275668.jpg',
      'https://shop.qa.foodlion.com/cdn-cgi/image/f=auto,q=80,dpr=1,h=324,w=324/https://d2d8wwwkmhfcva.cloudfront.net/800x/filters:fill(FFF,true):format(jpg)/d2lnr5mha7bycj.cloudfront.net/product-image/file/large_e7cbc2f3-bbe3-4fe9-9089-08d91938fc5b.jpg',
    ],
    priceForPersonal: '6.99',
    priceForCompany: '5.69',
    // "published": 'private',
    stock: 68,
  },
  {
    title: 'Canidae Grain Free PURE Elements Dry Cat Food',
    content:
      'Specially formulated to help control hairballs before they start, Meow Mix Hairball Control cat food is a tasty mix with chicken, turkey, salmon & ocean fish flavors. This wholesome recipe filled with essential vitamins and minerals along with high-quality protein make mealtimes irresistible!',
    category: 'Chats',
    typefood: 'Dry Cat Food',
    market: 'Canidae',
    quantity: '3.15lb',
    images: [
      'https://concordpetfoods.com/cdn/shop/products/33110-1656050874_480x480.jpg?v=1656521899',
      'https://concordpetfoods.com/cdn/shop/products/33110-1656050874_480x480.jpg?v=1656521899',
      'https://concordpetfoods.com/cdn/shop/products/33110-1656050873_480x480.jpg?v=1656521899',
      'https://concordpetfoods.com/cdn/shop/products/33110-1656050872_480x480.jpg?v=1656521899',
    ],
    priceForPersonal: '36.99',
    priceForCompany: '29.69',
    // "published": 'private',
    stock: 68,
  },
  {
    title: 'Pedigree Adult Beef and Vegetables Dry Dog Food',
    content:
      'Pedigree Adult Dry Dog Food Beef and Vegetables Flavor Scientifically proven shinier coat in 6 weeks Calcium and Phosphorous  for strong bones and teeth Dietary Fiber  for digestive system Protein  for strong muscles Vitamins and Minerals for strong immune system',
    category: 'Chien',
    typefood: 'Dry Dog Food',
    market: 'Canidae',
    quantity: '1.5kg',
    images: [
      'https://www.petexpress.com.ph/cdn/shop/products/10187821-Pedigree-Adult-Beef-and-Vegetables-Dry-Dog-Food-1.5kg-front_500x.jpg?v=1645169059',
      'https://www.petexpress.com.ph/cdn/shop/products/10187821-Pedigree-Adult-Beef-and-Vegetables-Dry-Dog-Food-1.5kg-front_500x.jpg?v=1645169059',
      'https://www.petexpress.com.ph/cdn/shop/products/10187821-Pedigree-Adult-Beef-and-Vegetables-Dry-Dog-Food-1.5kg-nutrients_500x.jpg?v=1645169059',
      'https://www.petexpress.com.ph/cdn/shop/products/10187821-Pedigree-Adult-Beef-and-Vegetables-Dry-Dog-Food-1.5kg-feeding-guide_500x.jpg?v=1645169059',
    ],
    priceForPersonal: '36.99',
    priceForCompany: '29.69',
    // "published": 'private',
    stock: 68,
  },
  {
    title: 'TURKEY & LAMB – LOW FAT',
    content:
      'ow fat food, but bursting with flavour – dieting doesn’t have to be difficult. We’ve created a delicious low fat dog food that will keep your furry friend full and fighting fit. It’s perfectly crafted to achieve maximum, protein-rich flavour with minimal fat, making it easy to keep any pup happy and healthy. With trim lamb and low-fat turkey, this protein-packed dry dog food delivers everything your dog needs and kept out anything they don’t. We’ve added in plenty of super food goodness, including the incredible hemp seed oil for nose-to-tail benefits you can really see. Our pet food formula is hypoallergenic and perfectly nutritionally balanced to provide everything your pup needs, with no grains, fillers, or artificial anything. If your pet has pancreatitis, consult with your vet to find out if this is the food for you. Our incredible low fat dog food is full of health benefits and the perfect choice to keep your dog fit and well. Try it today and see the improvements in your pup.',
    category: 'Chien',
    typefood: 'Ow fat food',
    market: 'Canidae',
    quantity: '1.5kg',
    images: [
      'https://cdn-kdkdj.nitrocdn.com/ZwsZPaCXrWeMecxsIfNhLxNHoDyGqwSn/assets/images/optimized/rev-47b64a9/www.petfoodaustralia.com.au/wp-content/uploads/2022/05/PFA-DogFood-Bag-Mock-1000x1000pxlowfatturkeylamb.png',
      'https://cdn-kdkdj.nitrocdn.com/ZwsZPaCXrWeMecxsIfNhLxNHoDyGqwSn/assets/images/optimized/rev-47b64a9/www.petfoodaustralia.com.au/wp-content/uploads/2022/05/PFA-DogFood-Bag-Mock-1000x1000pxlowfatturkeylamb.png',
      'https://cdn-kdkdj.nitrocdn.com/ZwsZPaCXrWeMecxsIfNhLxNHoDyGqwSn/assets/images/optimized/rev-47b64a9/www.petfoodaustralia.com.au/wp-content/uploads/2021/12/PFA-Mussels-1000x1000px.jpg',
      'https://www.petexpress.com.ph/cdn/shop/products/10187821-Pedigree-Adult-Beef-and-Vegetables-Dry-Dog-Food-1.5kg-feeding-guide_500x.jpg?v=1645169059',
    ],
    priceForPersonal: '36.99',
    priceForCompany: '29.69',
    // "published": 'private',
    stock: 68,
  },
  {
    title: 'ONLY NATURAL PET RAW BLENDS SKIN AND COAT DOG FOOD - 4 LB',
    content:
      'ow fat food, but bursting with flavour – dieting doesn’t have to be difficult. We’ve created a delicious low fat dog food that will keep your furry friend full and fighting fit. It’s perfectly crafted to achieve maximum, protein-rich flavour with minimal fat, making it easy to keep any pup happy and healthy. With trim lamb and low-fat turkey, this protein-packed dry dog food delivers everything your dog needs and kept out anything they don’t. We’ve added in plenty of super food goodness, including the incredible hemp seed oil for nose-to-tail benefits you can really see. Our pet food formula is hypoallergenic and perfectly nutritionally balanced to provide everything your pup needs, with no grains, fillers, or artificial anything. If your pet has pancreatitis, consult with your vet to find out if this is the food for you. Our incredible low fat dog food is full of health benefits and the perfect choice to keep your dog fit and well. Try it today and see the improvements in your pup.',
    category: 'Chien',
    typefood: 'Ow fat food',
    market: 'Canidae',
    quantity: '4lb',
    images: [
      'https://www.onlynaturalpet.com/cdn/shop/products/OnlyNaturalPetRawBlendsSkin_CoatFormulaRawInclusionDryDogFood4lb_1400x1400.jpg?v=1667331323',
      'https://www.onlynaturalpet.com/cdn/shop/products/OnlyNaturalPetRawBlendsSkin_CoatFormulaRawInclusionDryDogFood4lb_1400x1400.jpg?v=1667331323',
      'https://www.onlynaturalpet.com/cdn/shop/products/OnlyNaturalPetRawBlendsSkin_CoatFormulaRawInclusionDryDogFood4lbBackofBag_900x900.jpg?v=1667336028',
      'https://www.onlynaturalpet.com/cdn/shop/products/OnlyNaturalPetRawBlendsSkin_CoatFormulaRawInclusionDryDogFood4lbBackofBag_900x900.jpg?v=1667336028',
    ],
    priceForPersonal: '22.99',
    priceForCompany: '19.69',
    // "published": 'private',
    stock: 68,
  },
  {
    title: 'Arden Grange Puppy/Junior Large Breed',
    content:
      'Arden Grange Puppy/Junior Large Breed 12kg with Fresh Chicken and Rice is formulated to ensure a controlled growth rate - particularly important to help puppies reach their correct adult proportions, body shape and to attain the best of health. The delicious kibble is a perfect size for larger breeds.',
    category: 'Chien',
    typefood: 'Junior Large Breed ',
    market: 'ARDEN GRANGE',
    quantity: '12kg',
    images: [
      'https://www.thenaturalpetstore.co.uk/cdn/shop/products/154178282_700x.jpg?v=1667818189',
    ],
    priceForPersonal: '48.99',
    priceForCompany: '43.69',
    // "published": 'private',
    stock: 18,
  },
  {
    title: 'Arden Grange Adult Chicken & Rice Dry Dog Food',
    content:
      "Arden Grange Adult with fresh Chicken & Rice is suitable for small and medium breed adult dogs with normal activity levels, and is a complete, super premium pet food. Containing fresh chicken, a delicious and highly digestible protein source, Arden Grange Chicken & Rice is also suitable for larger breed dogs who prefer a smaller kibble, and includes beneficial additives such as prebitotics, joint supplements, krill and yucca extract to help support your dog's overall health and well-being.",
    category: 'Chien',
    typefood: 'Chicken ',
    market: 'ARDEN GRANGE',
    quantity: '6kg',
    images: [
      'https://www.thenaturalpetstore.co.uk/cdn/shop/products/54099_pla_arden_grange_chicken_rice_adult_dry_0_700x.jpg?v=1667819115',
      'https://www.thenaturalpetstore.co.uk/cdn/shop/products/2022_04_ardengrange_df_d_adult_chicken_front_6kg_1000x1000_pdp_700x.jpg?v=1687032532',
      '',
    ],
    priceForPersonal: '23.99',
    priceForCompany: '22.69',
    // "published": 'private',
    stock: 10,
  },
  {
    title: 'Arden Grange Cat Light Chicken & Potato',
    content:
      'Arden Grange’s Light cat food is lower in fat and calories than their standard adult cat food, but still delicious, made with 26% fresh chicken and 22% chicken meat meal. It’s designed for cats who are overweight, prone to weight gain or less active, such as older cats, neutered cats or those who are kept indoors. It’s also kind to sensitive digestions and a good choice for cats with allergies or intolerances, as it’s hypoallergenic, grain-free, and contains prebiotics and nucleotides that promote a healthy digestion and metabolism. Omega 3 and 6 plus glucosamine, MSM and chondroitin have been added to boost joint health and help your cat stay flexible, and there are added vitamins and minerals to promote good overall health.',
    category: 'Chats',
    typefood: 'Chicken & Potato',
    market: 'ARDEN GRANGE',
    quantity: '400g',
    images: [
      'https://www.thenaturalpetstore.co.uk/cdn/shop/products/154663190-1_500x.jpg?v=1667818209',
    ],
    priceForPersonal: '4.99',
    priceForCompany: '3.69',
    // "published": 'private',
    stock: 50,
  },
  {
    title: 'Arden Grange Kitten Chicken & Potato',
    content:
      'Arden Grange Chicken and Potato kitten food is designed with kittens in mind, with a small kibble size that packs in nutrients and calories. Recommended for kitten from 3 weeks to 1 year old, it’s also suitable for pregnant or lactating cats too.  Made with fresh chicken, this delicious kitten food contains prebiotics to promote healthy digestion and it’s also grain-free and hypoallergenic, making it a great choice for kittens and their mums who have sensitive tummies or allergies. Packed full of vitamins, minerals and nutrients, it’s a really healthy choice for your kitten, and the Omega fatty acids, glucosamine, MSM, chondroitin will help them stay at their flexible, playful best!',
    category: 'Chats',
    typefood: 'Chicken & Potato',
    market: 'ARDEN GRANGE',
    quantity: '400g',
    images: [
      'https://www.thenaturalpetstore.co.uk/cdn/shop/products/154663170-1_700x.jpg?v=1667818208',
    ],
    priceForPersonal: '15.99',
    priceForCompany: '14.69',
    // "published": 'private',
    stock: 10,
  },
  {
    title: 'Pet Munchies Fish Fillet Cat Treats 10g',
    content:
      'Pet Munchies 100% Gourmet Fish Fillet Natural Cat Treats are made with high quality, human-grade white fish fillets that have been gently airdried to lock in all their nutrients and their delicious flavour. The only other ingredient is a little vegetable protein.',
    category: 'Chats',
    typefood: 'Chicken & Potato',
    market: 'ARDEN GRANGE',
    quantity: '10g',
    images: [
      'https://www.thenaturalpetstore.co.uk/cdn/shop/products/168570474-1_700x.jpg?v=1667818269',
    ],
    priceForPersonal: '2.99',
    priceForCompany: '1.69',
    // "published": 'private',
    stock: 60,
  },
  {
    title: 'Pet Munchies Wild Salmon Strips',
    content:
      'These tasty doggy treats are made from natural quality human grade wild salmon, a natural source of Omega 3, which helps to promote skin and joint health and to keep your dog’s coat in great condition. They’re also high in protein and low in fat, giving your dog essential building blocks for health while preventing the pounds from piling on!',
    category: 'Chats',
    typefood: 'Salmon Strips',
    market: 'PET MUNCHIES',
    quantity: '80g',
    images: [
      'https://www.thenaturalpetstore.co.uk/cdn/shop/products/168570210-1_700x.jpg?v=1667818254',
    ],
    priceForPersonal: '3.99',
    priceForCompany: '2.69',
    // "published": 'private',
    stock: 9,
  },
];
